[package]
name = "fat32_fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.8"
hashbrown = "0.12.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
